name: "Code Standards"

on:
  push:
    branches:
      - main
      - develop
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: true

    name: Code Standards

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --working-dir=tools/php-cs-fixer

      - name: Execute code standards checking
        run: composer phpcsfixer-analyse
